### ISSUE TITLE
Mention nightly in Hello World tutorial

### ISSUE THREAD

**Issue by cooperra** [ebkalderon/amethyst#11]
As a new Rust user, this is the first time I ran into an unstable feature. This lead me to reading about the feature-gating system, distribution channels, and multirust, which was enlightening, but sidetracked me from the tutorial. 

Anyway, I think it would be helpful to new users like myself to add a note about distribution channels in the tutorial in case they encounter an error in hello_world like I did: 

`error: use of unstable library feature 'drain': recently added, matches RFC (see issue #27711)`

I see in #3 that this problem might go away by itself, but this is still worth considering in the meantime.

**Comment by ebkalderon** [comment]
Thanks for reporting this! While the *Getting Started* section mentions nightly Rust and Cargo and prerequisites, it might be better if it's mentioned more prominently on the first page of the book.

I have time to make the changes later today, though I'm a bit busy with university work ATM. If you can, please make a pull request with your changes, and I'll gladly review it. See the CONTRIBUTING.md file for details on how to contribute documentation.

**Comment by cooperra** [comment]
I'll handle this if you like.

**Comment by ebkalderon** [comment]
Thank you! I'll be free to review it in a few more hours.

**Comment by ebkalderon** [comment]
@cooperra, I have time to look at your pull request. I'll review it as soon as it comes in. Thanks again!

**Comment by ebkalderon** [comment]
Thanks for your help! Closed.
