### ISSUE TITLE
Reorganize project infrastructure

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/amethyst#13]
There are some major changes coming to our core infrastructure. Currently, the overall Amethyst project consists of three repositories: amethyst, amethyst_cli, and amethyst_opengl.

Amethyst is set for future expansion, and the current approach to organizing our code is not maintainable. I propose the following:

- [x] Consolidate the entire Amethyst engine into the main "amethyst" repository. All future engine code and text for the Amethyst Book will reside **only** in this repository.
  - [x] Split the Amethyst engine into separate sub-crates.
     - [x] Engine
     - [x] Renderer
  - [x] Have the "amethyst" crate re-export these crates as one API.

This might cause some breakage, but this must be minimized as much as possible, especially in other branches like [ecs](https://github.com/ebkalderon/amethyst/tree/ecs) and [gpures](https://github.com/ebkalderon/amethyst/tree/gpures). Let's use [Piston's approach for managing multiple crates under one repository](https://github.com/PistonDevelopers/piston) as prior art.

Progress has begun on the [reorg](https://github.com/ebkalderon/amethyst/tree/reorg) branch.

This is the engine-side counterpart of [Amethyst Tools issue #4](https://github.com/ebkalderon/amethyst_tools/issues/4).

**Comment by ebkalderon** [comment]
It seems that splitting the engine into separate sub-crates causes issues with unit testing (see the annotation in pull request #15). If anyone has better ideas on the reorganization process, please discuss them here.

**Comment by kvark** [comment]
We don't have this problem in [GFX](https://github.com/gfx-rs/gfx). Perhaps, you could follow the same structure?

We have most of the crates inside the same repository, and they are in sub-folders (`src/core`, `src/render`, `src/backend/gl`, etc). Each has its own tests. Then there is a "meta" crate, which is just an empty `src/lib.rs`, it depends on all the sub-crates via [Cargo.toml](https://github.com/gfx-rs/gfx/blob/master/Cargo.toml#L17). Thus, calling `cargo build` builds everything, calling `cargo test` tests everything. This meta crate doesn't need to be uploaded to `crates.io`, it's just for developer convenience.

**Comment by ebkalderon** [comment]
@kvark After playing around with my local copy of the repository, I can conclude that while `cargo build` does indeed build everything and `cargo clean` does clean everything, this behavior does not appear to extend to `cargo test`. Can you confirm?

**Comment by ebkalderon** [comment]
A general question: should the `amethyst_engine` crate exist? Or should its functionality be put in the top-level `amethyst` crate?

**Comment by kvark** [comment]
Isn't Amethyst a game engine? What is supposed to be in `amethyst_engine` then?

**Comment by ebkalderon** [comment]
It is indeed! I was wondering whether the code in `amethyst_engine ` should be moved to the top-level `amethyst ` crate, or if it should stay in its own crate.

**Comment by ebkalderon** [comment]
Engine restructuring has been completed with commit 449dd3a, so I'm closing this issue.

As of now, ebkalderon/amethyst_tools#4 remains open. The public 0.2.0 release will occur when that issue is resolved.
