### ISSUE TITLE
Redesign GPU resource management

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/amethyst#7]
The renderer needs to have a more robust resource handle design for it to be maintainable. The current situation with `state_static`, `state_dynamic`, and `types` is untenable in the long term. Perhaps a trait-based system for resources (a la gfx-rs) would help here.

This issue will track the progress of this feature's development. It must be completed before 0.2.0 "Explosive Cleric" reaches Crates.io!

* [ ] Backend Resources
  * [x] Define what a GPU resource really is (are state objects resources, just like textures?)
  * [x] Resources trait
  * [x] Factory trait
    * [ ] Creation
    * [ ] Binding
    * [ ] Destruction
  * [ ] Expand Backend trait
* [ ] Resource Handles
  * [ ] High-level API agnostic handles, created by Factories
  * [ ] Implement destructors for each handle
  * [ ] Resources struct and Handles struct (need alternative non-conflicting names)
    * [ ] Input resource data to Resources struct
    * [ ] Output Handles struct containing handles
  * [ ] Commands should refer to resource handles only
* [ ] More to come...

**Comment by ebkalderon** [comment]
Update: The current progress can be followed on the [gpures branch](https://github.com/ebkalderon/amethyst/tree/gpures).

**Comment by ebkalderon** [comment]
Idea: GPU resources are a separate concept from state objects, even though both are managed similarly. However, there are some marked differences in their construction and usage, and most next-gen APIs make the same distinction. Below are working definitions of both concepts.

* **Resource**
  * **Definition**: A chunk of structured data that is either pushed to or created directly on the GPU.
  * **Examples**: Buffer, sampler, render target, unlinked shaders.
* **State Object**
  * **Definition**: A collection of "switches" or "toggles" dictating how a certain piece of the graphics pipeline should process the given resources.
  * **Examples**: Pipeline state, blend state, depth-stencil state, rasterizer state, etc.

Remaining questions:

1. Are descriptor sets (basically packets of resources) considered resources themselves?

**Comment by ebkalderon** [comment]
After re-evaluating the goals of the project, I have decided that implementing the gameplay framework is more urgent than completing the renderer at this time. While the renderer is a critical component, this is a game engine, and as such people should be able to make games with it first.

As such, I am shelving this redesign and marking this as "stalled" until further notice. Priority will shift towards the thread-safe ECS implementation. If anyone else wants to work on this while I focus on issue #10, they are welcome to do so.

**Comment by kvark** [comment]
Did you consider using gfx-rs directly?

**Comment by ebkalderon** [comment]
I have indeed. However, I drafted the design of my renderer well before gfx-rs officially rolled out pipeline state object support. Incorporating gfx-rs into the renderer is back on the table, now that PSO support is fully baked. Hopefully, gfx-rs will develop a working Vulkan backend and then the renderer can be greatly simplified.

**Comment by ebkalderon** [comment]
If the renderer depends on GFX for rendering (issue #16) is implemented, this improvement will be invalidated.

**Comment by ebkalderon** [comment]
With the recent 0.2.0 release, the renderer now depends on gfx-rs, making this issue invalid. Closing.
